/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/macbook.glb --transform false 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/macbook.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['PROD-34805_1'].geometry} material={materials.ASSET_MAT_MR} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/macbook.glb')
